// Generated by scripts/textures/telnyashka/table/render.mjs — do not edit by hand.
// Layer boxes of the rendered still life in CSS px (scene 204x116), hover offsets in CSS px / deg.
export const TABLE_LAYOUT = {
  "width": 204,
  "height": 116,
  "base": {
    "x": 15,
    "y": 1.67,
    "w": 178.67,
    "h": 112.67
  },
  "sausage": {
    "x": 85.33,
    "y": 45,
    "w": 59.33,
    "h": 17,
    "dx": -2.98,
    "dy": -0.31
  },
  "slices": [
    {
      "x": 142,
      "y": 51.67,
      "w": 12.67,
      "h": 9.67,
      "dx": 2.95,
      "dy": 0.55,
      "rot": -7
    },
    {
      "x": 151.33,
      "y": 56.67,
      "w": 12.67,
      "h": 9,
      "dx": 3.69,
      "dy": 0.91,
      "rot": 9
    },
    {
      "x": 143.67,
      "y": 59.67,
      "w": 13,
      "h": 9.33,
      "dx": 4.12,
      "dy": 2.04,
      "rot": -8
    },
    {
      "x": 153,
      "y": 49.67,
      "w": 12.67,
      "h": 8.67,
      "dx": 3,
      "dy": 0.08,
      "rot": 6
    },
    {
      "x": 135,
      "y": 62.33,
      "w": 13.33,
      "h": 9.67,
      "dx": 2.56,
      "dy": 2.81,
      "rot": -10
    }
  ],
  "hit": {
    "from": [
      90.13,
      49.14
    ],
    "to": [
      138.56,
      54.25
    ],
    "slices": [
      [
        148.46,
        56.68
      ],
      [
        157.65,
        60.94
      ],
      [
        150.1,
        64.2
      ],
      [
        159.34,
        53.61
      ],
      [
        141.7,
        66.93
      ]
    ]
  }
} as const
