// Generated by scripts/textures/telnyashka/table/render.mjs — do not edit by hand.
// Layer boxes of the rendered still life in CSS px (scene 204x116), hover offsets in CSS px / deg.
export const TABLE_LAYOUT = {
  "width": 204,
  "height": 116,
  "base": {
    "x": 8,
    "y": 1.67,
    "w": 191,
    "h": 114.33
  },
  "sausage": {
    "x": 76,
    "y": 52,
    "w": 69,
    "h": 19.67,
    "dx": -2.98,
    "dy": -0.31
  },
  "slices": [
    {
      "x": 142,
      "y": 60,
      "w": 14.67,
      "h": 11,
      "dx": 2.95,
      "dy": 0.55,
      "rot": -7
    },
    {
      "x": 152.67,
      "y": 65.67,
      "w": 14.67,
      "h": 10.33,
      "dx": 3.69,
      "dy": 0.91,
      "rot": 9
    },
    {
      "x": 143.67,
      "y": 69.33,
      "w": 15,
      "h": 10.67,
      "dx": 4.12,
      "dy": 2.04,
      "rot": -8
    },
    {
      "x": 154.67,
      "y": 57.33,
      "w": 14.67,
      "h": 10,
      "dx": 3,
      "dy": 0.08,
      "rot": 6
    },
    {
      "x": 134,
      "y": 72.33,
      "w": 15,
      "h": 11,
      "dx": 2.56,
      "dy": 2.81,
      "rot": -10
    }
  ],
  "hit": {
    "from": [
      81.47,
      56.77
    ],
    "to": [
      137.77,
      62.71
    ],
    "slices": [
      [
        149.29,
        65.54
      ],
      [
        159.96,
        70.49
      ],
      [
        151.19,
        74.28
      ],
      [
        161.93,
        61.97
      ],
      [
        141.42,
        77.46
      ]
    ]
  }
} as const
